Seir process
czbiohub/nf-epigen pull request #20
Opened 2020-10-23 18:17 UTC by phoenixAja

Many thanks to contributing to nf-core/epigen!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/epigen branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/epigen)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/epigen/tree/master/.github/CONTRIBUTING.md

2020-10-27 16:52 UTC, lucymli requested changes
Hi @phoenixAja, this runs on my machine with the two docker containers. 
I made a couple of changes, and requested one additional change, which is to allow users to specify a few arguments for the model to run (see the last comment on seir_model.py).

2020-10-27 16:52 UTC, lucymli commented on bin/seir_model.py
> +    leaf_times = (leaf_times + shift - first_timeseries_date)*365.25
I pushed a commit that modifies these couple of lines to make the coal_times and leaf_times match the times from the times series data.

2020-10-27 16:52 UTC, lucymli commented on bin/seir_model.py
> +    coal_times = (coal_times + shift - first_timeseries_date)*365.25
Also in this commit, I removed extraneous lines that generate variables that are not used later on.

2020-10-27 16:52 UTC, lucymli commented on bin/seir_model.py
> +        population=int(4e7),
Is it possible to read in a config file that the user can specify for each region? For example the population, incubation_time, recovery_time, num_samples, haar_full_mass should be adjusted per region.

2020-10-27 16:57 UTC, phoenixAja commented on bin/seir_model.py
> +        population=int(4e7),
yeah totally, do you think that should be parameters that are passed in as flags (and maybe have a csv file if processing multiple regions?) Or maybe we could get that information publicly from somewhere and have another process that could get that information.

2020-10-27 16:58 UTC, phoenixAja commented on bin/seir_model.py
> +    coal_times = (coal_times + shift - first_timeseries_date)*365.25
cool thanks, my language interpreter wasn't working correctly on tesla so i didn't catch that stuff!

2020-10-27 17:14 UTC, phoenixAja commented on bin/seir_model.py
> +        population=int(4e7),
for num_samples could we get that information from the provided newick tree? Like count the number of leaves or something like that?

2020-10-28 22:10 UTC, lucymli commented on bin/seir_model.py
> +        population=int(4e7),
I think the best solution is to save to have default values to run if the user doesn't specify any. And then read these values in as either flags or csv files. The latter is better if processing multiple regions, as you mentioned in your comment, or when there are many parameters to specify.

Looking at the parameters that need to be specified for this model:

- population is geography dependent and should be specified by the user
- incubation_time and recovery_time can have default values (the current values are fine for the default values); in the future it would be great to compile a list of suggested values for different infectious diseases.
- num_samples and haar_full_mass should be specified by the user; these are hyperparameters that will affect how well the model runs.

2020-10-28 23:34 UTC, phoenixAja commented on bin/seir_model.py
> +        population=int(4e7),
ok cool, i think a csv file should be used for the case where you have multiple regions with different values for each parameter, otherwise if they use the flag option then we can use the same parameter values for the multiple locations.

2020-10-29 18:56 UTC, phoenixAja commented
population and num_samples csv should look like these files used for the test config:
https://github.com/czbiohub/test-datasets/blob/epigen/testdata/epigen/num_samples.csv
https://github.com/czbiohub/test-datasets/blob/epigen/testdata/epigen/population.csv

2020-10-29 23:08 UTC, lucymli approved these changes
This works for me! I tested with my own parameter csvs too.

2020-10-29 23:08 UTC, lucymli commented on bin/01_curate_time_series.R
> +    if ((any(diff(x$cumulative_cases)<0, na.rm=TRUE))) {
I added this line to handle NAs in the raw timeseries data.

2020-10-29 23:09 UTC, lucymli commented
Feel free to merge when you're ready @phoenixAja

2020-10-29 23:10 UTC, merged